### ISSUE TITLE
contains viruses

### ISSUE THREAD

**Issue by ye-sus** [IllusionMods/KKManager#106]
https://www.virustotal.com/gui/file/4f7494a7a8f86a66f690a44e9956fe6e566eac6399b886072d2e86d9b62ac1e6/detection
![Tidak berjudul](https://user-images.githubusercontent.com/121365263/209453834-54a8b1ce-1535-4feb-843b-adfd67de1d00.jpg)

**Comment by ManlyMarco** [comment]
That's only 2/59, and at least one of them isn't an actual detection but a heuristics warning. I suggest looking up how to decide if a file is safe or not and how to notice false detections.

https://www.hybrid-analysis.com/sample/4f7494a7a8f86a66f690a44e9956fe6e566eac6399b886072d2e86d9b62ac1e6
