### ISSUE TITLE
Updater Stuck.

### ISSUE THREAD

**Issue by ReemX** [IllusionMods/KKManager#110]
With P2P on updater just stuck on " Waiting for files to download" been stuck like that for 30 minutes. With P2P off it gets the files just fine in about 2 minutes.

**Comment by ReemX** [comment]
just wanted to mention that even without P2P the speed of downloads improved significantly!

**Comment by ManlyMarco** [comment]
If you have a slow HDD the startup can take a very long time, at the moment there isn't much I can do about that, it is what it is.

**Comment by ReemX** [comment]
Slow HDD?🤣 My man I'm running this on a raid 0, 2 NVME SSD with 6 Gb transfer rates.

**Comment by ManlyMarco** [comment]
You can see what exactly is happenning in the log, it's almost certainly just taking very long to read and hash existing files.

**Comment by ManlyMarco** [comment]
Is this still an issue in latest version?

**Comment by ManlyMarco** [comment]
Should be resolved as well as possible with https://github.com/IllusionMods/KKManager/commit/6d703df254c97b5e387644b8022a12074bd43950
