### ISSUE TITLE
P2P mode wants to download already existing mods

### ISSUE THREAD

**Issue by slormo** [IllusionMods/KKManager#112]
When I use the P2P mode on 0.21.2, it wants to download a bunch of files, even though they are already installed.

![Screenshot 2023-02-13 150157](https://user-images.githubusercontent.com/104801833/218494214-c76bc4ec-6635-423a-8cf1-25e6026ca33a.png)

**Comment by slormo** [comment]
The files I have appear to be the exact same as the ones it wants to download. It also wants to download new files, but they appear black instead of green.

**Comment by ManlyMarco** [comment]
[_release.zip](https://github.com/IllusionMods/KKManager/files/10726719/_release.zip)
See if this build fixes the issue,
