### ISSUE TITLE
Allow seeding in the background or in main window

### ISSUE THREAD

**Issue by Skelun** [IllusionMods/KKManager#114]
At the moment the only option to seed is to leave open the mod update window.  This takes 2 spaces in my taskbar and it's annoying. I would like to help seed, but I don't want to leave these windows open.

So it would be awesome if we could leave open as a windows service, or at least a single window.

**Comment by ManlyMarco** [comment]
Not going to implement this for now. In the meantime you can update from the game launcher, this way you will only have the single update window.

**Comment by ManlyMarco** [comment]
Added in 10a0c869b3f24c01d4ec5eb8dc8fbdd3eecd299a 9a28c7416323721d917f72ece603ec19da3b8c16
