### ISSUE TITLE
discrepancy in downloadable packages

### ISSUE THREAD

**Issue by yarrmateys** [IllusionMods/KKManager#116]
there's some discrepancy between files to download using the updater, both mod manager and standalone. in p2p mode for koikatsu it says there's nothing to download, while in normal mode it says there's 700+ mb to download. the files already all exist, except their folder name is different (it exists under evaan while updater says it should be evan). this doesn't seem to happen in p2p mode.
i use the non-p2p mode to check if updates are available since it gets the list faster than p2p, then if there are any i switch to p2p to download them faster.

**Comment by ManlyMarco** [comment]
There is no way to switch to p2p without hashing everything. The p2p sources can be out of sync since they are updated much less frequently to not shed seeds, so it's best to stick to only one of the methods.
