### ISSUE TITLE
[Feature] Minimize Button on Mod Updater

### ISSUE THREAD

**Issue by NeverEndingCycle** [IllusionMods/KKManager#119]
Can we please get a minimize button on the mod updater? Especially with seeding, it's really frustrating to have to leave the window open all the time. A minimize to tray would be even better and support the P2P system because it's never visible unless you're looking for it. But for now a regular minimize would seriously do wonders for UX.

**Comment by ManlyMarco** [comment]
#114

**Comment by ManlyMarco** [comment]
Added in 10a0c869b3f24c01d4ec5eb8dc8fbdd3eecd299a 9a28c7416323721d917f72ece603ec19da3b8c16
