### ISSUE TITLE
Infinite research

### ISSUE THREAD

**Issue by KyoTensu** [IllusionMods/KKManager#12]
Hi, I'm here because for a moment now, KKManager doesn't want to update the mods.
When I click on the update button, the research starts but it's like it will never finish (I didn't test for a very very long time like one day but I can say that it is way longer than before).
Maybe it is the fault of my connection but it does not seem to have changed.
I really like this software and it's sad that I can't update anymore.

**Comment by ManlyMarco** [comment]
Make sure you have the latest version and make sure that KKManager is actually stuck (open task manager and see if it is using any CPU or HDD). If it's noticeably using resources then let it run, if you have a very slow HDD it can take some time. If not, send the KKManager.log file after letting it run for some time.

**Comment by KyoTensu** [comment]
Ok so I installed the latest version of KKManager (I didn't knew there was other versions of this software because I use it with the flashbangz modpack) and I launch a research, it is using my random memory so I will let it run during the afternoon and come back. Thanks for the help 😄 !

**Comment by KyoTensu** [comment]
finally, i cancelled the research and when I relaunched it, it works perfectly and now I'm downloading the updates. the research was really fast like before so I don't know why it was not working but now it is.
Thank you for helping me and I just want to say that your software is really cool and helpful 😃 !

**Comment by ManlyMarco** [comment]
It's included in the flashbangz modpack? Can you send me the UpdateSources file from that repack?

**Comment by KyoTensu** [comment]
You want the files from the modpack version of KKManager or the link of the modpack ? I'm sorry I'm not sure to understand (I'm french).

**Comment by ManlyMarco** [comment]
The KKManager\UpdateSources file from the modpack, not the link.

**Comment by KyoTensu** [comment]
[[Tool] KKManager v0.7.0 - Mod Updater.zip](https://github.com/IllusionMods/KKManager/files/4208855/Tool.KKManager.v0.7.0.-.Mod.Updater.zip)

**Comment by ManlyMarco** [comment]
Thank you.
