### ISSUE TITLE
downloader literally just stoping mid download

### ISSUE THREAD

**Issue by zacman2000** [IllusionMods/KKManager#121]
it's not going beyond 0.7 percent, and the download speed somehow dropped to zero
![issue with updater](https://user-images.githubusercontent.com/43187983/229596198-4a57a463-ac4e-41b4-af7e-44b20427c439.PNG)

**Comment by ManlyMarco** [comment]
Make sure the port you chose for p2p is open, and try restarting the update. If it keeps stalling, turn off p2p to go back to old updater.

**Comment by zacman2000** [comment]
i went to the old updater, but now the download is getting interrupted
![showing the stalling](https://user-images.githubusercontent.com/43187983/229639309-32241c24-cfa4-4bbe-b716-65dad9770cfa.PNG)
 and not completing fully

**Comment by zacman2000** [comment]
Failed to load zipmod from "C:\Program Files (x86)\Steam\steamapps\common\Koikatsu Party\mods\Sideloader Modpack\Vodka\[Vodka] Fairy Fencer acc v1.0.0.zipmod" with error: Ionic.Zip.ZipException: C:\Program Files (x86)\Steam\steamapps\common\Koikatsu Party\mods\Sideloader Modpack\Vodka\[Vodka] Fairy Fencer acc v1.0.0.zipmod is not a valid zip file
   at void Ionic.Zip.ZipFile.Initialize(string fileName)
   at SideloaderModInfo KKManager.Data.Zipmods.SideloaderModLoader.LoadFromFile(string filename) in D:/SVN/KKManager/src/KKManager.Core/Data/Zipmods/SideloaderModLoader.cs:line 146
   at Task KKManager.Data.Zipmods.SideloaderModLoader.TryReadSideloaderMods(string modDirectory, ReplaySubject<SideloaderModInfo> subject, CancellationToken cancellationToken, SearchOption searchOption)+(string file) => { } in D:/SVN/KKManager/src/KKManager.Core/Data/Zipmods/SideloaderModLoader.cs:line 86 ---> Ionic.Zip.ZipException: Cannot read that as a ZipFile
   at void Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at void Ionic.Zip.ZipFile._InitInstance(string zipFileName, TextWriter statusMessageWriter)
   at void Ionic.Zip.ZipFile.Initialize(string fileName) ---> Ionic.Zip.BadReadException: Could not read block - no data!  (position 0x00000000)
   at int Ionic.Zip.SharedUtilities._ReadFourBytes(Stream s, string message)
   at void Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   this is the error that says it can't download the zip file for the maximo animations for chara studio.

**Comment by ManlyMarco** [comment]
That's just an unfinished download probably, run the update again to fix it.

**Comment by zacman2000** [comment]
i managed to get the first updates working, but now i got a new issue, now i can't download the last 14 gigabytes of the sideloader mod, it keeps sailing it failed to download cause the names where too long or the directore's is, i have no idea what that means as i haven't changed anything

**Comment by zacman2000** [comment]
Reason(s) for failing:
Failed to apply update C:\Program Files (x86)\Steam\steamapps\common\Koikatsu Party\mods\Sideloader Modpack - Bleeding Edge\CCCCP\#hardmod\@getuploader\koiemo167\koiemo167@getuploader  [TICK-TACK]rollup_shorts v1.0\[TICK-TACK]rollup_shorts v1.0\abdata\chara\r_shortjeans\rollup_shorts.unity3d because of an IO issue - Could not find a part of the path.
Failed to apply update C:\Program Files (x86)\Steam\steamapps\common\Koikatsu Party\mods\Sideloader Modpack - Bleeding Edge\CCCCP\#hardmod\@getuploader\koiemo167\koiemo167@getuploader  [TICK-TACK]rollup_shorts v1.0\[TICK-TACK]rollup_shorts v1.0\abdata\chara\r_shortjeans\thumb\rollup_shorts_thumb.unity3d because of an IO issue - The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. this is the result i get when i try and download the missing part of the update

**Comment by zacman2000** [comment]
the error keeps happening, what should i do?

**Comment by ManlyMarco** [comment]
> the error keeps happening, what should i do?

Don't use the bleeding edge pack, at least until it's fixed enough to work.

**Comment by zacman2000** [comment]
understood

**Comment by zacman2000** [comment]
how will i know when it's fixed enough to work?

**Comment by ManlyMarco** [comment]
> how will i know when it's fixed enough to work?

It almost never is, that's the whole point. If you want a modpack without bugs then just use the normal ones.
