### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by LocalVoidwalker** [IllusionMods/KKManager#122]
i dont understand how to make it work after deleting the old files and unpacking it into the KKManager folder

**Comment by ManlyMarco** [comment]
Just replace existing files and run the exe as usual. Don't download source code by mistake.

**Comment by LocalVoidwalker** [comment]
I'd have done just that if I still had the exe. I deleted it think the readme said to

**Comment by LocalVoidwalker** [comment]
Readme recommended deleting all the old files except settings so I did

**Comment by ManlyMarco** [comment]
Watch the video guide linked on the download page.
