### ISSUE TITLE
Fail to update new mod files(without error)

### ISSUE THREAD

**Issue by aqssxlzc** [IllusionMods/KKManager#125]
Hi, I am using the latest version KK Manager, with P2P mods updater.  
It runs normally,  finish all downloading jobs and told me KK manager finished update.
But when I double check the files in mods folder.  The files are not renewed.
Then I check for new updates.  the very same modes are still needs to update even I have downloaded them minutes ago by KK.

**Comment by ManlyMarco** [comment]
Update KKManager to the latest version.

**Comment by ManlyMarco** [comment]
Are you closing the updater window after it's finished? The update isn't finished until you click the ok button.

**Comment by aqssxlzc** [comment]
Yes. I closed updater window, and the information like "update xx mods on xxx files" show up. Everything looks normally,  but not file change.  And If I click check update again, the very same mod updates shows.

**Comment by FFFtuanfff** [comment]
I did click the ok button. but everytime i check for the updates it keep showing the same files I had been download many times.

**Comment by PacoMadreja** [comment]
Same here

**Comment by ManlyMarco** [comment]
Send your KKManager.log files, or the updater log if you use it through the launcher.

**Comment by PacoMadreja** [comment]
> Send your KKManager.log files, or the updater log if you use it through the launcher.

Unfortunately, the log file only shows todays actions.

**Comment by ManlyMarco** [comment]
@PacoMadreja What language are you running KKManager in?

@aqssxlzc Can you try setting KKManager language to English and see if that resolves the issue?

If changing language doesn't help, can you try this debug build? It will have much more verbose logging. [kkm_debug.zip](https://github.com/IllusionMods/KKManager/files/11325760/kkm_debug.zip)

**Comment by PacoMadreja** [comment]
> @PacoMadreja What language are you running KKManager in?
> 
> @aqssxlzc Can you try setting KKManager language to English and see if that resolves the issue?
> 
> **Edit:** This should now be fixed in the latest release https://github.com/IllusionMods/KKManager/releases/tag/v0.22.0.1

Always in English

**Comment by aqssxlzc** [comment]
> @PacoMadreja What language are you running KKManager in?
> 
> @aqssxlzc Can you try setting KKManager language to English and see if that resolves the issue?
> 
> **Edit:** This should now be fixed in the latest release https://github.com/IllusionMods/KKManager/releases/tag/v0.22.0.1

v0.22.0.1 fixed this bug,  great work, thanks!
