### ISSUE TITLE
[Feature] Sort/filter by ContentsKind

### ISSUE THREAD

**Issue by HijackHornet** [IllusionMods/KKManager#127]
Sideloader tries to sort items into character, map, studio items. But i still find that some maps are downloaded with the main pack. In the sideloader tab, it would be nice to be able to filter out maps and studio item to remove them.

**Comment by ManlyMarco** [comment]
Not really possible, it's handled on the [modpack side](https://github.com/BetterRepack/SideloaderModpackTracker/issues). Also currently it's not possible to selectively download mods without disabling them.
