### ISSUE TITLE
[Feature] Remember deleted items

### ISSUE THREAD

**Issue by ghost** [IllusionMods/KKManager#128]
It would be nice if KKM could remember what sideloader mod has been deleted through its UI so that it wont offer to redownload them next time you do a mod update

**Comment by ManlyMarco** [comment]
You can avoid redownloading by disabling instead of deleting the mods.

**Comment by HijackHornet** [comment]
If I delete mod it's also to spare some disk space. Disabling isn't really helping. Anyway it's a suggestion, you don't have to do it.

**Comment by ManlyMarco** [comment]
I thought about it and it's difficult to do properly, what if user deletes a zipmod because they want to redownload it for example.
This would be resolved by #59
