### ISSUE TITLE
I was confused when download all the file and did not see KKManager.exe Don't know if you can show me more specific?

### ISSUE THREAD

**Issue by longbro5567** [IllusionMods/KKManager#13]

**Comment by longbro5567** [comment]
![image](https://user-images.githubusercontent.com/61102004/74598963-8dfdb480-50ad-11ea-935e-61b06c488d94.png)
This is when I extract the file.

**Comment by longbro5567** [comment]
Can you please show me the specific step to get the app?

**Comment by ManlyMarco** [comment]
You downloaded the source code. Download the latest build from the releases instead. https://github.com/IllusionMods/KKManager/releases

**Comment by longbro5567** [comment]
Thanks for your help~

Vào 18:44, CN, 16 Th2, 2020 MarC0 <notifications@github.com> đã viết:
