### ISSUE TITLE
KKmanager删去了KKS原有的zipmods

### ISSUE THREAD

**Issue by Tarsesr** [IllusionMods/KKManager#131]
我使用KKmanager对KKS的mod进行了更新，点击了“清理重复的zipmods”和“修复文件和文件夹权限”（这一项点击后程序不知道为什么会卡住），更新完后，我发现我一些原有人物卡的zipmods不见了，这是怎么回事？

**Comment by Tarsesr** [comment]
现在相当部分的人物卡读取时会提示：“缺少XXXzipmod”（而这些zipmods原本存在且可用），我应该如何修复这个问题？

**Comment by ManlyMarco** [comment]
Using the cleanup tool will remove any zipmod files with duplicate GUIDs. If you did not make any backups and the mods you need are not in the updater then your best bet is to try a file recovery program or redownload the mods. If the updater doesn't fix the missing mod warnings then make sure you are running the latest KKManager version.

**Comment by BullOnMars** [comment]
Suggestion: KKManager needs a non-destructive way to handle duplicate mods deletion, for example, moving duplicate mods to Recycle Bin instead of deleting them instantly.

**Comment by ManlyMarco** [comment]
Added a setting for removing to recycle bin.
