### ISSUE TITLE
Updating .zipmods with "vx.xx.xx" is stopping Koikatsu cards from recognizing them

### ISSUE THREAD

**Issue by ShoopDaWoop123** [IllusionMods/KKManager#139]
Cards with required zipmods that have had their names updated with the relevant version number next to them stops the cards that use them from recognizing them, and as a result fails to load them.  I have tested this multiple times and every time the problem is fixed by renaming the .zipmod to what koikatsu is displaying what is "missing".

**Comment by ManlyMarco** [comment]
This doesn't sound right, the filenames have nothing to do with what mod gets loaded or not as long as it's inside the mods directory and has a zipmod or zip extension. Make sure the zipmods are actually being loaded by the game. Unless you are editing the manifest, in which case never edit the guids.

**Comment by ShoopDaWoop123** [comment]
After some more checking around, cleaning up duplicate mods and manually removing previous zipmods that were placed by me before the repack added them seemed to fix it.  Although in my looking of the config, there seems to be some KKS_MaterialEditors .zipmods in the KK_MaterialEditor folder, like AI Shaders, etc.

**Comment by ManlyMarco** [comment]
Avoid manually editing the sideloader modpack folders, use kkmanager to update them and place any of your own mods outside of them. KK and KKS often share the same mods.
Sounds like you fixed the issue so I'll close this as resolved.
