### ISSUE TITLE
Still as same as the old one

### ISSUE THREAD

**Issue by longbro5567** [IllusionMods/KKManager#14]
![image](https://user-images.githubusercontent.com/61102004/74605783-c3ca8980-50fd-11ea-93bc-d43d6e383c26.png)
You give me the latest version and when I unzip, it still as same as usual. No exe was found.

**Comment by ManlyMarco** [comment]
Please reuse the old issue when you still have the same problem.

![aaaa](https://user-images.githubusercontent.com/39247311/74610230-924bc100-50f1-11ea-9711-4d3ee0724a34.PNG)

![aaaaaaaaa](https://user-images.githubusercontent.com/39247311/74610229-91b32a80-50f1-11ea-9ed6-93fd5e676f5d.PNG)

**Comment by longbro5567** [comment]
Thanks and sorry for disturb you this time😖😖

Vào 01:22, T.2, 17 Th2, 2020 MarC0 <notifications@github.com> đã viết:

**Comment by ManlyMarco** [comment]
Don't worry about it, I updated the readme to make it clearer where to download from.

**Comment by longbro5567** [comment]
I was very confused at first but thank to you. Now I can actually use the
mod. Thanks~

Vào 08:39, T.2, 17 Th2, 2020 MarC0 <notifications@github.com> đã viết:
