### ISSUE TITLE
my download suffers a Unexpected crash while updating mods {System.InvalidOperationException: Client is already started}

### ISSUE THREAD

**Issue by subkate** [IllusionMods/KKManager#143]
i have try everthing im capable of reinstalling looking up the error if anyone knows how to fix this it only started happaning after update 23.0 i tryed older versions but nothing worked for months sorry if this is a super simple issue and my just dumb and help would be appreciated   
![Screenshot 2023-11-27 000543](https://github.com/IllusionMods/KKManager/assets/152158762/9e269cd6-8c91-469d-a7c0-d2af9769c206)

**Comment by ManlyMarco** [comment]
Make sure there is only one instance of KKManager running and try updating from the game launcher instead.

**Comment by subkate** [comment]
i reinstalled the launcher and turned off p2p that was the problem i had turned off p2p but need to do both, thank you

**Comment by subkate** [comment]
> Make sure there is only one instance of KKManager running or try updating from the game launcher instead. Maybe also turn off checking updates on startup and/or turn off p2p mode.

thank you the issue was i needed to ture of p2p and reinstall the game i had disable p2p before so i thought it was not the problem.

sorry if i mess something English is not my first language thanks again
