### ISSUE TITLE
Add a feature for updating plugins

### ISSUE THREAD

**Issue by linhong1994** [IllusionMods/KKManager#147]
I see that the plugin page contains a website for plugins, and the efficiency of updating plugins by opening this website is very low,

Can you add an update plugin feature to the software

Although the naming convention for each plugin version is different and the corresponding game is also different, the same plugin is the same,

It should not be difficult to adapt a set of rules for each plugin, but the workload is relatively high

I still really hope to have this feature

**Comment by ManlyMarco** [comment]
Updating plugins is not possible on purpose, since it's very likely to break when not following author instructions.

**Comment by ManlyMarco** [comment]
Plugins have the URL in their metadata.
