### ISSUE TITLE
about mods black spots

### ISSUE THREAD

**Issue by voicesound14789** [IllusionMods/KKManager#153]
how  can i remove the black spots ，many kind of skin has this problem (On Groin)，is it a bug？how can fix
![螢幕擷取畫面 2024-04-02 205449](https://github.com/IllusionMods/KKManager/assets/165857539/4ca10def-a198-49d1-809d-de5df750e089)

**Comment by ManlyMarco** [comment]
Looks like ambient occlusion or shadow. In that case it's not really a bug, try changing scene effect settings and graphics settings.

**Comment by voicesound14789** [comment]
> Looks like ambient occlusion or shadow. In that case it's not really a bug, try changing scene effect settings and graphics settings.

but that is initialize setting

**Comment by ManlyMarco** [comment]
Closing since it has nothing to do with KKManager. Try asking on the discord server for the game.
