### ISSUE TITLE
Infinite updating

### ISSUE THREAD

**Issue by shinDOZER** [IllusionMods/KKManager#16]
Hello! After a few successful usages of auto-update, now KKManager opens a window with a wrench-girl, says "Searching for mod updates...", progress is "N/A", the Cancel-button doesn't do anything. 
It suppose to show me a window with a list of mods to update.
I've tried renaming mods folder (so there are no mods to update), rebooting PC, launching as administrator - not helping, however it worked just a few hours ago.

**Comment by ManlyMarco** [comment]
This can happen if there's an issue connecting to the file host, it will keep retrying essentially forever. It'll be fixed in the next release.
