### ISSUE TITLE
Check local zipmod status against zipmod database & re-download missing zipmods

### ISSUE THREAD

**Issue by realisticdreamer114514** [IllusionMods/KKManager#160]
**Basically "git checkout . " but for zipmods.** 
As far as I know I assume KKmanager only "updates" by replacing zipmods with new versions & download brand new ones, like a "git pull".
I don't remember it checking for zipmods that should be there in the current version of the modpack but are missing, most likely due to failed updates or accidental deletions. 
Can you change KKManager so it can also do something like a "git checkout . " (notice the dot), where it brings the local zipmod folder to something exactly like the BR database online (the one by one zipmod downloading page)?
If this is already done by the current version pls kindly remind me how to enable it & close this, I just come back from a long time of not touching anything KK.

**Comment by ManlyMarco** [comment]
Basically, no, not going to happen for technical reasons.

**Comment by ManlyMarco** [comment]
The modpack maintenance is separate from any patches and such. Modpacks are updated continously so there's nothing like a release to make checkpoints out of. The backend also has no support for this and it would mess up current p2p scheme by not having all clients participate in latest modpack sources.
