### ISSUE TITLE
Mod updating fails to properly even start after list of mods to be updated is acquired?

### ISSUE THREAD

**Issue by Timtee** [IllusionMods/KKManager#165]
Trying to update my mods for AI Shoujo but... Am encountering an error and not entirely sure why.

Here's the error specifically at the end of the updater log:
[Updater] System.InvalidOperationException: Client is disposed
   at KKManager.Updater.Sources.TorrentUpdater.<Start>d__8.MoveNext() in D:\SVN\KKManager\src\KKManager.Updater\Sources\TorrentUpdater.cs:line 359
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at KKManager.Updater.Windows.ModUpdateProgressDialog.<ModUpdateProgress_Shown>d__9.MoveNext() in D:\SVN\KKManager\src\KKManager.Updater\Windows\ModUpdateProgressDialog.cs:line 247

Dunno if this is a bug others are experiencing, or if it's just a corrupted file on my end, or otherwise I'm not sure. (also I have p2p transfer off because it honestly actually slows the time it takes to acquire the list of mods to be updated so... yeah.)

**Comment by ManlyMarco** [comment]
Make sure you are using latest version of KKManager. This error can only happen with p2p turned on.

**Comment by Timtee** [comment]
> Make sure you are using latest version of KKManager. This error should only be possible if p2p was turned on at some point. If you turned it off try restarting KKManager.

Mmm that is possible for the latter portion. Also yes it is on the latest version. (I had updated the client itself prior to trying to update the mods.) I guess it's not necessarily a bug then or anything but an error that occurs if you don't restart the app after turning P2P off. Which if so, thanks for the answer.

**Comment by ManlyMarco** [comment]
If you can find exact steps to reproduce this issue I can fix it, since it's still a bug.

**Comment by Timtee** [comment]
I merely just turned off p2p without reloading the client, plus also was
first launch after updating to current version. Otherwise I do not know how
else you could replicate it.
