### ISSUE TITLE
Missing zipmods after an update

### ISSUE THREAD

**Issue by rher0000** [IllusionMods/KKManager#169]
After updating the mods some of the cards are highlighted in red in the manager, and it says that some zipmods for items are missing. Is there a way to download them from the manager?

**Comment by ManlyMarco** [comment]
Make sure your kkmanager is up to date and try updating again.

**Comment by rher0000** [comment]
> Make sure your kkmanager is up to date and try updating again.

it is the latest version.

**Comment by rher0000** [comment]
![Screenshot 2024-06-02 230912](https://github.com/IllusionMods/KKManager/assets/164656202/9f125312-9fc5-4261-966e-c0bd0779ecc7)

**Comment by ManlyMarco** [comment]
Maybe you manually placed zipmods inside of the modpack folders? They would be removed in that case.
