### ISSUE TITLE
"fix files and folders and permissions" not working and some other stuff

### ISSUE THREAD

**Issue by maxlefou** [IllusionMods/KKManager#17]
For some reasons, half of the features of KKManager are not working. Like, I can sucessfully move a card from a place to another, but only if there's no card of the same name. The move command doesn't do anything either as well as gender change.

I thought it was a problem with permissions in my userdata folder so I used teh command in the fixes, but the takeown command displays this error and doesn't do anything else:
```
Error: incorrect syntax, the "y" value is not permitted for the option "/d"
```

What permissions the folder and its content is supposed to have?

(Tested on 0.9.1 and 0.9.2)

**Comment by ManlyMarco** [comment]
There is no system for overwriting cards currently, it'll have to be added.

> The move command doesn't do anything either as well as gender change.
Those are not implemented yet.

> takeown command displays this error and doesn't do anything else
What version of Windows are you running and exactly what do you do to trigger the issue?

**Comment by maxlefou** [comment]
If it's not implemented, why not hiding these options in the release version? I mean, it would avoid confusing users.

I'm on windows 10. To trigger the error, i just have to click on `Tools` / `Fixes` / `Fix file and folder permissions` then accept admin permissions. Then the terminal window appears and displays this error.

**Comment by ManlyMarco** [comment]
Can you check if the latest release still has the same issue with the permission fix?

**Comment by maxlefou** [comment]
Updated to 0.12.1 and still having the same error on that particular thing. 
Except that it mentions `Y` and `/D` and not `y` and `/d`

(also the right click on a card doesn't show a menu anymore. Is this intended?)

**Comment by ManlyMarco** [comment]
What happens if you run this through your system's Run dialog? Does it show the same error? It assumes you have a directory `D:\test`
`cmd /C echo off & cls & title Fixing permissions... & takeown /F "D:\test" /R /SKIPSL /D Y & icacls "D:\test" /grant everyone:F /T /C /L & pause`

The menu got removed to avoid confusion.

**Comment by maxlefou** [comment]
same error.

Full path is `C:\Games\koikatsu`

**Comment by ManlyMarco** [comment]
Looks like it's a locale issue. Different system languages can have different valid values for the /D command from the default Y/N for some reason. You should be able to get it to work by removing the `/D Y` part of it.

**Comment by maxlefou** [comment]
Indeed i've just checked the help about the takeown command and the program expects a `O` instead of a `Y` for the `/D` option... That's incredibly stupid from micro$oft... 🤦‍♂️ 

I guess a fix would be to make kkmanager fetch the locale of win10 and swap Y with whatever letter is used depending of the locale. But is it worth it? 🤷‍♂️

**Comment by ManlyMarco** [comment]
Can you try if this build works for you?
[KKManager.Core.dll.zip](https://github.com/IllusionMods/KKManager/files/4670153/KKManager.Core.dll.zip)

**Comment by maxlefou** [comment]
yep, it worked with this file ^^

**Comment by ManlyMarco** [comment]
Can you test if this build still has the mapping error?

[KKManager.Core.dll.zip](https://github.com/IllusionMods/KKManager/files/4671772/KKManager.Core.dll.zip)

**Comment by maxlefou** [comment]
everything is succesful now :)

**Comment by ManlyMarco** [comment]
The method grew into a monstrosity at the end of it https://github.com/IllusionMods/KKManager/blob/master/KKManager.Core/Util/ProcessTools.cs#L57
