### ISSUE TITLE
Koikatsu sunshine Rx11 update error after updating kk manager to v1.4.1 latest version

### ISSUE THREAD

**Issue by Wapcoz** [IllusionMods/KKManager#186]
I am attaching three screenshots here. One shows error when i click on update in kk initSetting, and other is exception error & report.

![update error](https://github.com/user-attachments/assets/f50cd412-8464-4240-8506-ce0fee4f129d)

![exception error](https://github.com/user-attachments/assets/c7ffc8cb-f00a-47fa-b443-65d65fdc5bdb)

![report](https://github.com/user-attachments/assets/afbbb5d2-5e26-4d40-b9d3-6e08f2eb8700)

**Comment by ManlyMarco** [comment]
Reinstall KKManager, some of its files are missing.

**Comment by Wapcoz** [comment]
ok. Thank you for your reply. My antivirus just automatically quarantined one of its dll file, which i have now restored & added to trust list.
