### ISSUE TITLE
Totally up to date yet mod loader says I have to up date still.

### ISSUE THREAD

**Issue by IlleagalToob** [IllusionMods/KKManager#187]
I can't update any of my mods because KKManager is not to date, yet I've deleted and downloaded the newest version multiple times. What do I do?
![Capture](https://github.com/user-attachments/assets/bc8c7d34-e13a-4262-8860-1aee1aca80d6)

**Comment by ManlyMarco** [comment]
Your version is severely out of date. Download the latest version from the patreon page linked in releases.
