### ISSUE TITLE
Don't have a .exe

### ISSUE THREAD

**Issue by TecFrost** [IllusionMods/KKManager#19]
My KKManager isn't a .exe and instead is a .sln.
Is it because I'm missing something? This seems to happen when downloading things from github for me.
Whenever I try to open my current KKManager.exe I get an error that says "API response: ResourceNotExists" and I can't update, change or view anything, hence wanting to update.
Currently have v0.7.0.34712

**Comment by TecFrost** [comment]
Update: It only seems to work for me when I download it from the 'releases' page. Weird...

**Comment by ManlyMarco** [comment]
This is how github works, the main page is for source code so you download the source code. Like instructed in the readme, you need to download a compiled release from the releases page.
