### ISSUE TITLE
enable multiselect on SideloaderModsWindow

### ISSUE THREAD

**Issue by rainbowB0SS** [IllusionMods/KKManager#21]
It would be really convenient to disable mods in bulk since there are a lot of mods. It is enabled for PluginsWindow. Is there a reason this is specifically disabled for SideloaderModsWindow?

I did a quick check and it looks like enabling multi works fine (am able to enable/disable/delete selected mods).

**Comment by ManlyMarco** [comment]
Looks like an oversight, I fixed it. 7eb9631d099b201d8871956ba4f8627529f2a844
