### ISSUE TITLE
download speed  slow·····

### ISSUE THREAD

**Issue by 2374060397** [IllusionMods/KKManager#23]
If  display the download address may be faster，go directly to the download page

**Comment by ManlyMarco** [comment]
This should be fixed by now. If the problem persists, please create a new issue.

**Comment by jalil49** [comment]
What is considered the reasonable download speed? seeing quite a few downloads below 80 KB/s

**Comment by ManlyMarco** [comment]
It should be going at least 5MB/s in latest version.

**Comment by jalil49** [comment]
Ah I see, I didn't download KKmanager myself as it came with a patch/mod so I had 0.14.0 version
