### ISSUE TITLE
Add http/socks5 proxy support

### ISSUE THREAD

**Issue by mirazas852** [IllusionMods/KKManager#25]
I have a problem, where KKManager downloads only a part of the mods i select  and fails to download some of them. For example there was an 8 GB SideLoader Modpack file and the KKManager downloaded 6 GB. Other 2 GB were not downloaded and when i tried to download them later 5 times or so, it still did not work. Using the newest 0.11.0 KKManager. Puting the KKManager.log and the error message here.
![Error message](https://user-images.githubusercontent.com/66939567/84630530-bfb84800-aef4-11ea-8970-4d6fd74b2a9a.JPG)
[KKManager.log](https://github.com/IllusionMods/KKManager/files/4778727/KKManager.log)

**Comment by ManlyMarco** [comment]
Try using this build, just extract it to your existing kkmanager folder and replace. Afterwards send me the resulting log if it still fails. [_build.zip](https://github.com/IllusionMods/KKManager/files/4780291/_build.zip)

**Comment by mirazas852** [comment]
Yeah it still failed. so here you go:
[KKManager.log](https://github.com/IllusionMods/KKManager/files/4780805/KKManager.log)

**Comment by ManlyMarco** [comment]
Your connection to the download servers is timing out for some reason. The servers work fine so it's most likely something about your internet connection that's blocking them. Make sure any firewalls on your network allow for FTP traffic. You can ping ai-shoujo.com to see if you have connection at all.

The "successfully updated" message box incorrectly shows 532 successful updates while actually all of them failed because the servers timed out. I'll fix it in next release to show the real number.

**Comment by mirazas852** [comment]
I pinged the site and it seems that i have connection with it so at least some good news. Also I am pretty sure I enabled FTP traffic but it still doesn't work. I'll try to fix this problem myself somehow, but still thank you for your help and advise. I appreciate it.

**Comment by mirazas852** [comment]
Actually, maybe it did something. I uninstalled the game and downloaded  it again and now everything works fine.

**Comment by ManlyMarco** [comment]
I doubt reinstalling the game was what helped, maybe it was some temporary outage.

**Comment by yyg12345678910** [comment]
> 我怀疑重新安装游戏是否会有所帮助，也许是暂时的停机。

some continent users always have this problem .Useing network proxy function can fix this.I use  billing software  to forward the ftp network traffic through my socks5 proxy wich  server is in USA.can you add the http/socks5 proxy function?
like this:
![tor](https://user-images.githubusercontent.com/25651447/86374399-170d3500-bcb7-11ea-8348-5af789b32ec5.PNG)

**Comment by yyg12345678910** [comment]
> I doubt reinstalling the game was what helped, maybe it was some temporary outage.

some continent users always have this problem .Useing stable VPN or network proxy  can fix that.I use billing software to forward the process' ftp network traffic  through  socks5 proxy (which server is in USA) to my PC,then i can download all the mod.
Can you add the http/socks5 proxy function?
like this:
![tor](https://user-images.githubusercontent.com/25651447/86375235-fe514f00-bcb7-11ea-90d8-df280356ae5f.PNG)

**Comment by yyg12345678910** [comment]
> I doubt reinstalling the game was what helped, maybe it was some temporary outage.

some continent users always have this problem .Useing stable VPN or network proxy can fix that.I use billing software to forward the process' ftp network traffic through socks5 proxy (which server is in USA) to my PC,then i can download all the mod.
Can you please add the http/socks5 proxy function?
like this:
![tor](https://user-images.githubusercontent.com/25651447/86377195-994b2880-bcba-11ea-8fe1-a24797cb2c1c.PNG)
Some engineering software have this function to make user updating faster.You know

**Comment by ShaneT02** [comment]
Im also having the same problem but im having trouble with it

**Comment by ManlyMarco** [comment]
It looks like it has been fixed some time ago, DefaultWebProxy is used if it's configured in the OS.
