### ISSUE TITLE
the program stuk at "searching for mod update"  in V0.12.0 V0.11.0 V0.10.1 V0.10.0

### ISSUE THREAD

**Issue by yyg12345678910** [IllusionMods/KKManager#28]
And i cant exit the process normally.Felling like some loop logic problem.
By the way,the car loading is stuck at "3 loaded so far" after opening the process .maybe that is the same bug 
system:win10 professional edition 10.0.18363,and amd ryzen 5 2600x+rtx2070+32g 

![kk](https://user-images.githubusercontent.com/25651447/86368901-584e1680-bcb0-11ea-8c8f-64d93e4b1780.PNG)

**Comment by yyg12345678910** [comment]
AI-shoujo，the newest version

**Comment by yyg12345678910** [comment]
well , i find that is the "cards loading" bug. i drop most car then the updating can work . i have 312 cards in chara folder

**Comment by yyg12345678910** [comment]
well , i find that is the "cards loading" bug. i delete most car then the updating can work . i have 312 cards in chara folder

**Comment by yyg12345678910** [comment]
well , i find that is the "cards loading" bug. i delete most cards then the updating can work . i have 312 cards in chara folder

**Comment by yyg12345678910** [comment]
> well , i find that is the "cards loading" bug. i delete most cards then the updating can work . i have 312 cards in chara folder

This just work onece,it happened again after i download one floder mods.Then I use StandaloneUpdater.exe to download,but i find that has the sam bug.it seem like some DLL file's problem

![dll](https://user-images.githubusercontent.com/25651447/86419605-3da68c80-bd06-11ea-926e-0e838a5d8c2b.PNG)

**Comment by yyg12345678910** [comment]
The log file.Please check them
[KKManager.log](https://github.com/IllusionMods/KKManager/files/4867824/KKManager.log)
[StandaloneUpdater.log](https://github.com/IllusionMods/KKManager/files/4867825/StandaloneUpdater.log)

**Comment by yyg12345678910** [comment]
the V0.9.3 can still updated successfully. and i can connect server in browser
![kk9](https://user-images.githubusercontent.com/25651447/86435625-fda9ce80-bd32-11ea-80e6-b2624cc4d905.PNG)
![ftp](https://user-images.githubusercontent.com/25651447/86435636-03071900-bd33-11ea-95a2-f223300f6cd4.PNG)

**Comment by yyg12345678910** [comment]
please cheak the log file.
[KKManager.log](https://github.com/IllusionMods/KKManager/files/4868091/KKManager.log)

**Comment by ManlyMarco** [comment]
This should be fixed by now. If the problem persists, please create a new issue.
