### ISSUE TITLE
Crash while updating mods HS2, AIS

### ISSUE THREAD

**Issue by turtlbrdr** [IllusionMods/KKManager#32]
Having an issue where KKManager is unable to update either HS2 or AIS. This has been happening since the 13th, and I just revisited the issue today after assuming the servers for the packs were on the fritz for the day. 

Every time I try to update the modpacks on HS2 or AIS, a dialog pops up saying the update failed, while the window with the progress bar says "Crash while updating mods. aborting." 

I took the log file from a HS2 update crash.
[KKManager.log](https://github.com/IllusionMods/KKManager/files/4944881/KKManager.log)

I have copies of the program for each of the three games, and they are updated to 0.12.0 (part of the original reason I suspected the servers were down, I updated the version of the program, but it still didn't work.). 

I have disabling every bit of network protection on this computer, and nothing has changed or updated on the network I'm on for several months, and have been having no issues keeping a connection.

**Comment by turtlbrdr** [comment]
An update, tried using it again today. I'm still having the same issue with the HS2-bound manager, but the one I have for Koikatsu was able to find update the compatibility pack just fine.

**Comment by ManlyMarco** [comment]
It looks like conditional checks for all update packages return false for some reason, which results in no updates being seen as compatible with your game. This is either an issue with your game install or the server config, you'll want to ask @ScrewThisNoise for help with this.

**Comment by ManlyMarco** [comment]
This should be fixed by now. If the problem persists, please create a new issue.
