### ISSUE TITLE
This program deleted the map I was using

### ISSUE THREAD

**Issue by maskelihileci** [IllusionMods/KKManager#34]
![Ekran_Alnts (4)](https://user-images.githubusercontent.com/41159853/93154443-4820d180-f70c-11ea-895e-2181e08c0e58.png)

There is no map now, I have to reload it
You really need to be careful while using this program, it can delete the mods you have searched for hours.

**Comment by ManlyMarco** [comment]
Do not place your own mods inside any of the Sideloader Modpack folders, they are reserved for the automatic updater.
