### ISSUE TITLE
No luck finding the .exe

### ISSUE THREAD

**Issue by CorazonXtreme** [IllusionMods/KKManager#40]
First time using GitHub, i downloaded 2 files 1 from the main page and the releases page.
have no idea what im doing tbh, but i can't find a .exe anywhere
also couldnt find a video to help. know u said something about downloading a source code from someone elses issue.
but no clue if im doing that correctly.

**Comment by ManlyMarco** [comment]
Go to the releases page and click the big bold Download link in the latest release. There are detailed instructions and links in the readme.
