### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by ARDEACT** [IllusionMods/KKManager#43]
It's the same issue as the one below, it's always updating and never gets anywhere. Checking it's usage, it's not doing anything, no CPU, network or storage usage.

**Comment by ARDEACT** [comment]
![image](https://user-images.githubusercontent.com/46211295/103943078-73865c80-50ff-11eb-9c2d-65e15a48f484.png)

**Comment by ManlyMarco** [comment]
Servers are currently under high load, try again later.
