### ISSUE TITLE
Enhancement: Let KKManager remember the last window size

### ISSUE THREAD

**Issue by calscks** [IllusionMods/KKManager#44]
### Current behaviour:
After resizing KKM's window, close KKM and then re-open KKM again. The window size resets to its original size, but somehow it still remembers how far the split panel has moved.

### Requested behaviour:
Allow KKM to remember the last window size so we don't have to re-scale the window size every time we re-open the application.

**Comment by ManlyMarco** [comment]
Done, thanks for the suggestion!
