### ISSUE TITLE
KKManager slow downloads

### ISSUE THREAD

**Issue by LozoTrioxide** [IllusionMods/KKManager#50]
Hey,

Ive noticed with version 0.16 that the download speeds are sitting between 0 - 300kb/s which is very slow, would this be a server problem or a me problem? Its been like it for around 3 days in a row now

if it helps, im trying to download the sideloader modpack and the animations for main game and studio.

Thanks :)

**Comment by ManlyMarco** [comment]
Servers are overloaded at the moment because a lot of people are trying to update.
