### ISSUE TITLE
UpDate issue

### ISSUE THREAD

**Issue by meenoname** [IllusionMods/KKManager#52]
Hi guys,
From some time KK Manager can't update Experimental Mods. It's stucks always at the same point

![Untitled-1](https://user-images.githubusercontent.com/87861475/126781437-3e52e40c-0faa-4dcf-9535-c1e239e2b7c2.jpg)

Maybe someone can help me to understand what's going wrong here.

**Comment by ManlyMarco** [comment]
The directory structure is too deep, either move the game to a directory like "D:\HS2" or wait until it gets cleaned up on the server. Please report issues with the modpack on the discord server, issues here are for KKManager itself and I don't have control over what's on the server.
