### ISSUE TITLE
Slow download speed whit the mod updater

### ISSUE THREAD

**Issue by zhxpz** [IllusionMods/KKManager#55]
its always below 1mb/s, its very rare to go faster than 1mb/s and when does its like for 1 or 2 seconds only, i have 100/100 mbs of internet connected by ethernet

**Comment by zhxpz** [comment]
![Captura de pantalla 2021-09-01 182051](https://user-images.githubusercontent.com/89879311/131762114-bbb67e91-25a0-4b9d-b772-659009cadb6f.png)
its imposible with this speed :(

**Comment by ManlyMarco** [comment]
There's too many people trying to update, unfortunately that's the norm now because of the massive size of the HS2 modpacks.

**Comment by Elryyyyyyyy** [comment]
Very Unlikely that soooo many people would update, its most likely your server beeing too slow.

**Comment by Elryyyyyyyy** [comment]
@zhxpz 
> ![Captura de pantalla 2021-09-01 182051](https://user-images.githubusercontent.com/89879311/131762114-bbb67e91-25a0-4b9d-b772-659009cadb6f.png) its imposible with this speed :(

@ManlyMarco
> There's too many people trying to update, unfortunately that's the norm now because of the massive size of the HS2 modpacks.

It has nothing to do with the amount of users, it cant be that much on a niche simulator.
Its either a bad downloader or the Server is really slow, which is not reasonable with your big Patreon.

**Comment by Elryyyyyyyy** [comment]
Please fix this, just to be fair to your patreons and the users.

**Comment by ManlyMarco** [comment]
Reply in the other issue https://github.com/IllusionMods/KKManager/issues/66#issuecomment-962585414

**Comment by SuperSteed007** [comment]
> Reply in the other issue [#66 (comment)](https://github.com/IllusionMods/KKManager/issues/66#issuecomment-962585414)

Hello, I cant seem to find the KKManager application when I download the new version. I didnt know where to ask for help and I didnt want to start a new thread. Im still stuck on 0.13 and havent been able to figure this out.

**Comment by ManlyMarco** [comment]
@SuperSteed007 Don't post unrelated questions in existing threads, just start a new issue or ask for help on the discord server.

**Comment by GoAwayNow** [comment]
I get that increasing download speeds isn't likely to be an option, but the ability to resume downloads after a connection breaks would go a long way to making things more... well, useable (Assuming that's even possible with FTP, IDK).

Some mods are very large and always end up breaking connection, becoming functionally impossible to download through the updater. I spent five days trying repeatedly to download a single 800mb mod that kept failing.

**Comment by x94fujo6rpg** [comment]
The solution for me  
I will manually update those files that are over 100MB after check for updates  
[https://sideload.betterrepack.com/download/](https://sideload.betterrepack.com/download/)
You can use downloader like aria2  

After that, check for updates again and let KKM handle the smaller files automatically

**Comment by yyuurrii34** [comment]
my idealism suggestion to this issue is to bring in the P2P downloader (or a plugin such as Aria2)

**Comment by QWdfASer** [comment]
![image](https://user-images.githubusercontent.com/117020566/198879774-3d78a2a4-0834-4fef-93c9-b6c5310e7633.png)
Not only is it dead slow at literally every time of the day (tested at 9am as well as 3pm, 10pm, 2am, 5am etc), it keeps failing when a node "concludes", restarting that particular node and showing an error message, as shown above. P2P would really be an additional solution, since the requirement is to have enough people to make it faster for everyone, and as you described, servers are starting to be an issue.

**Comment by NICENCEiver** [comment]
> my idealism suggestion to this issue is to bring in the P2P downloader (or a plugin such as Aria2)

Can you teach me how to operate？

**Comment by Jojo11ee** [comment]
Is there a link to the plugin Aria2 as I am having trouble finding it anywhere.

**Comment by x94fujo6rpg** [comment]
The weird thing is
When using a browser or aria2 or something like that, the download speed is very fast.

I watched the connection today when I used the update and found that they are FTP-DATA.
Could this be why it is so slow?

**Comment by yyuurrii34** [comment]
> The weird thing is When using a browser or aria2 or something like that, the download speed is very fast.
> 
> I watched the connection today when I used the update and found that they are FTP-DATA. Could this be why it is so slow?
> 
> ![](https://camo.githubusercontent.com/054fb853c4864c375159647b73b4824f2ec9315dbae47d430a9ea0379f280015/68747470733a2f2f692e696d6775722e636f6d2f7436374d70454c2e706e67)

well tried,I did sort of test similar to yours and it suggested that the FTP transfering by default has a QOS,and the parallel threads for a single connection can only be 5 at the maximum

**Comment by yangluo0901** [comment]
Quick question, I downloaded most of the contents (avg around 200kb/s, slow, but acceptable), but stuck at the rest of them (extremely slow down speed 18kb/s), will clicking cancel delete downloaded content?

**Comment by ManlyMarco** [comment]
Canceling will only remove unfinished files.

**Comment by ManlyMarco** [comment]
Should finally be resolved in 0.21.0

**Comment by yangluo0901** [comment]
Thank you for the update : )

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ManlyMarco** [comment]
There's still some issues that need to be fixed so the release is delayed for a bit.
