### ISSUE TITLE
how do i update the kkmanager?

### ISSUE THREAD

**Issue by Poebonn** [IllusionMods/KKManager#58]

**Comment by ManlyMarco** [comment]
Follow the instructions on download page of the latest version.
https://github.com/IllusionMods/KKManager/releases/tag/v0.18.0

**Comment by Poebonn** [comment]
> Follow the instructions on download page of the latest version.
> https://github.com/IllusionMods/KKManager/releases/tag/v0.18.0

the thing is i dont understand the instruction, do i copy the extracted file to the koikatsu party file?

**Comment by IDontHaveIdea** [comment]
Inside the directory of Koikatsu Party create a directory usually is named like this:

[UTILITY] KKManager

if you don't have it already.  Inside that directory unpack  the contents of **"KKManager_v0.18.0.7z"** archive.
