### ISSUE TITLE
download speeds

### ISSUE THREAD

**Issue by rdmkk** [IllusionMods/KKManager#69]
![image](https://user-images.githubusercontent.com/98652357/151664918-9aae3645-3640-463a-b5b6-c3fa7fc84e80.png)
my max download speed is 200kb/s
is this a problem with the server or is my internet just bad?

**Comment by ManlyMarco** [comment]
Looks like there's heavy traffic now, I'm getting around 1MBps. It helps if you can download in off-peak hours.

**Comment by ManlyMarco** [comment]
Closing as duplicate of #55
