### ISSUE TITLE
Where is kkmanager.exe

### ISSUE THREAD

**Issue by nothingman936** [IllusionMods/KKManager#7]
New to all this, so possible silly question. Can't find the kkmanager exe in the file that I downloaded. 
Help?

**Comment by ManlyMarco** [comment]
![Capture](https://user-images.githubusercontent.com/39247311/71049625-4b6a3b00-2143-11ea-8301-712642a0f841.PNG)

**Comment by longbro5567** [comment]
What do you mean the source code?
