### ISSUE TITLE
Application not found

### ISSUE THREAD

**Issue by SuperSteed007** [IllusionMods/KKManager#72]
Hello, I cant seem to find the KKManager application when I download the new version. I have looked at the read me and downloaded the latest zip file. I didnt know where to ask for help, Im still stuck on 0.13 and havent been able to figure this out.

**Comment by ManlyMarco** [comment]
Where are you downloading it from? The releases are in .7z archives not .zip
Check the patreon post linked in releases for the latest release and installation instructions.

**Comment by SuperSteed007** [comment]
Figured out my issue, thank you
