### ISSUE TITLE
KKManager window doesn't show up

### ISSUE THREAD

**Issue by nizhuan-jjr** [IllusionMods/KKManager#76]
I can only close the window and restart it, yet still the same issue.
![2022-03-10_074357](https://user-images.githubusercontent.com/3255986/157560476-a31772a5-cd53-4b22-bf3e-693ecd818dda.png)

The issue occurs occasionally, and I can only fix it by deleting all the content under [UTILITY] KKManager and extracting the files from the lastest 7z into the folder.

**Comment by ManlyMarco** [comment]
You can't resize it? Send the kkmanager.log file after the bug happens.

**Comment by nizhuan-jjr** [comment]
> You can't resize it? Send the kkmanager.log file after the bug happens.

There's no window to resize. I'll post the log file the next time it occurs.

**Comment by nizhuan-jjr** [comment]
[KKManager.log](https://github.com/IllusionMods/KKManager/files/8758782/KKManager.log)
The issue happens again.

**Comment by ManlyMarco** [comment]
Log looks normal, does the process keep running or does it close?

**Comment by nizhuan-jjr** [comment]
The process keeps running without showing up its window.

**Comment by MetalIzanagi** [comment]
My apologies for throwing my hat in here but I just had this happen and managed to figure out how to get the window back without having to delete everything. It seems like when this happens the KK Manager window isn't disappearing; it's actually just stuffing itself offscreen for some reason.

If you click the button for KK Manager that will be sitting in the taskbar when it does what OP described, you can press Alt+Spacebar together, and either click on or use the arrow keys to select "Move" in the dropdown menu that should appear near the top left-hand corner of your screen. Once you do that the window should appear as a really long, thin bar on the screen and you can then resize it normally afterwards, and it will be fine the next time you launch it.

**Comment by nizhuan-jjr** [comment]
> My apologies for throwing my hat in here but I just had this happen and managed to figure out how to get the window back without having to delete everything. It seems like when this happens the KK Manager window isn't disappearing; it's actually just stuffing itself offscreen for some reason.
> 
> If you click the button for KK Manager that will be sitting in the taskbar when it does what OP described, you can press Alt+Spacebar together, and either click on or use the arrow keys to select "Move" in the dropdown menu that should appear near the top left-hand corner of your screen. Once you do that the window should appear as a really long, thin bar on the screen and you can then resize it normally afterwards, and it will be fine the next time you launch it.

Thank you for the solution! I'll try it next time.

**Comment by ManlyMarco** [comment]
Oh, that's interesting. @nizhuan-jjr can you send me your KKManager.settings file after the bug happens?

**Comment by nizhuan-jjr** [comment]
[KKManager.settings.zip](https://github.com/IllusionMods/KKManager/files/8836916/KKManager.settings.zip)
The issue occured again, and I used the method mentioned above to resize the window out. Here is the setting file zip.

**Comment by ManlyMarco** [comment]
> [KKManager.settings.zip](https://github.com/IllusionMods/KKManager/files/8836916/KKManager.settings.zip) The issue occured again, and I used the method mentioned above to resize the window out. Here is the setting file zip.

So you moved the window and then sent the setting file? I need the setting file before the window is fixed, right click on taskbar and close from there.
Try removing the setting file and see if that triggers the issue.

**Comment by nizhuan-jjr** [comment]
> 

Removing the setting file does not trigger the issue. The next time it occurs, I can send you the unfixed setting file.
