### ISSUE TITLE
Clean up duplicate zipmod and Look for updates

### ISSUE THREAD

**Issue by Hentai02** [IllusionMods/KKManager#77]
Clean up duplicate zipmods, those cleaned up zipmods will also appear in the update list when updating again.
![image](https://user-images.githubusercontent.com/54672936/157648076-ef83b317-4c39-489c-b1aa-f00f99a0204d.png)
![image](https://user-images.githubusercontent.com/54672936/157648102-8e6cd8d4-8e81-4ef5-97b0-442cd0d95885.png)

[sena] vehicle4 v1.0.0.0.zipmod will still appear in the update list no matter how many times it is updated.
![image](https://user-images.githubusercontent.com/54672936/157647771-8064b529-6ee2-47f3-9f05-5fa1f4de840a.png)

**Comment by ManlyMarco** [comment]
Resolved in 0.21.0
