### ISSUE TITLE
Question: How to convert koikatsu type cards to koikatsu Sunshine cards?

### ISSUE THREAD

**Issue by lainflkr** [IllusionMods/KKManager#78]
I have tried hex editor but no luck. I am wondering what is the tag name (identifier) and value corresponding to koikatsu and koikatsu Sunshine type card?

**Comment by lainflkr** [comment]
Chinese Simplified
问题：如何将 Koikatsu 类型的卡转换为 Koikatsu Sunshine 卡？ 我试过十六进制编辑器，但没有运气。我想知道 koikatsu 和 koikatsu Sunshine 类型卡对应的标签名称（标识符）和值是什么？

Japanese
質問：コイカツタイプのカードをコイカツサンシャインカードに変換するにはどうすればよいですか？ 16進エディタを試しましたが、うまくいきませんでした。コイカツとコイカツサンシャインタイプのカードに対応するタグ名（識別子）と値は何ですか？

German
Frage: Wie konvertiere ich Karten vom Typ Koikatsu in Karten vom Typ Koikatsu Sunshine? Ich habe den Hex-Editor ausprobiert, aber kein Glück. Ich frage mich, wie der Tag-Name (Bezeichner) und der Wert der Karte vom Typ Koikatsu und Koikatsu Sunshine entsprechen.

French
Question : Comment convertir des cartes de type Koikatsu en cartes Koikatsu Sunshine ? J'ai essayé l'éditeur hexadécimal mais sans succès. Je me demande quel est le nom de la balise (identifiant) et la valeur correspondant à la carte de type koikatsu et koikatsu Sunshine ?

Ukrainian
Запитання: Як конвертувати карти типу Koikatsu в карти Koikatsu Sunshine? Я пробував шістнадцятковий редактор, але безрезультатно. Мені цікаво, яка назва тегу (ідентифікатор) і значення відповідають картці типу koikatsu та koikatsu Sunshine?

Spanish
Pregunta: ¿Cómo convertir tarjetas tipo Koikatsu a tarjetas Koikatsu Sunshine? Probé el editor hexadecimal pero no tuve suerte. Me pregunto cuál es el nombre de la etiqueta (identificador) y el valor correspondiente a la tarjeta tipo koikatsu y koikatsu Sunshine.

Amharic
ጥያቄ፡ የKoikatsu አይነት ካርዶችን ወደ ኮይካሱ ሰንሻይን ካርዶች እንዴት መቀየር ይቻላል? ሄክስ አርታዒን ሞክሬአለሁ ግን ምንም ዕድል የለም። የሚገርመኝ የመለያ ስም (መለያ) እና እሴት ከ koikatsu እና koikatsu Sunshine አይነት ካርድ ጋር የሚዛመደው ምንድን ነው?

Hindi
प्रश्न: कोइकात्सु प्रकार के कार्ड को कोइकात्सु सनशाइन कार्ड में कैसे बदलें? मैंने हेक्स संपादक की कोशिश की है लेकिन कोई भाग्य नहीं है। मैं सोच रहा हूं कि टैग नाम (पहचानकर्ता) और कोइकात्सु और कोइकात्सु सनशाइन प्रकार के कार्ड से संबंधित मूल्य क्या है?

Greek
Ερώτηση: Πώς να μετατρέψετε κάρτες τύπου Koikatsu σε κάρτες Koikatsu Sunshine; Δοκίμασα το hex editor αλλά χωρίς τύχη. Αναρωτιέμαι ποιο είναι το όνομα της ετικέτας (αναγνωριστικό) και η τιμή που αντιστοιχεί στην κάρτα τύπου koikatsu και koikatsu Sunshine;

**Comment by ManlyMarco** [comment]
It's best to let KKS convert KK cards by itself since it's a fairly complicated process when including plugin data.
