### ISSUE TITLE
How to make KKmanager download one file at a time?

### ISSUE THREAD

**Issue by Vaiox** [IllusionMods/KKManager#79]
KKmanager downloads 4 to 5 files at a time, is there a way to make it download one file or only the mods we want?

**Comment by ManlyMarco** [comment]
Why would you want it to download only 1 at a time? It downloads from multiple servers to get better download speeds, you might be stuck downloading at 100kbps without that.

**Comment by Vaiox** [comment]
> Why would you want it to download only 1 at a time? It downloads from multiple servers to get better download speeds, you might be stuck downloading at 100kbps without that.

Oh, so its server that's not giving full speed. I am getting 400-500 KBps speed where my real speed is between 2-8 MBps, that's why I thought instead of downloading 4 files at 400 KBps why not download one file at 400 KBps so it will download fast.
But I didn't know it's server that is slow.

**Comment by ManlyMarco** [comment]
The servers are fairly fast but there's a lot of people downloading, try during off-hours for faster speeds.
