### ISSUE TITLE
A tiny bug.

### ISSUE THREAD

**Issue by wits-fe** [IllusionMods/KKManager#8]
When I used the "Look for updates" in kkmanager 0.9.2, it showed that some mods can be updated(below):

![202001301845](https://user-images.githubusercontent.com/58023436/73444629-ee91af80-4393-11ea-9966-12482522799c.png)

But I've already installed the 2019/02/01 upadte and the After School and Darkness DLC, I tried download the things it listed and made a backup before that. Then I found that it downloaded the contents which aren't targeted the After School version. The following imgs show the differences:

![free](https://user-images.githubusercontent.com/58023436/73445303-5d233d00-4395-11ea-9390-e2861818c27f.png)
![free-as](https://user-images.githubusercontent.com/58023436/73445306-5f859700-4395-11ea-8ab8-22b52b704dcf.png)

The first img comes from kkmanager, the second is my backup file.

If you have the 2019/02/01 upadte DLC at hand,  you can find the differences between these two manuals (one is under the setup folder, the other under the setup_as folder. ) One manual is for the game which having not installed the After School DLC, the other for having.

I think the correct logic of kkmanager is that it shouldn't mark these files as updates on games which are After School and later patches, since these files are not the contens of that.
Thank you for the great work!

**Comment by CriticaI** [comment]
I'm having a similar issue. I guess downloading these again would not be advisable sinc eit will break the game?

![image](https://user-images.githubusercontent.com/46763554/74054435-5bcdc200-49de-11ea-93ed-d95d8d5731e8.png)

The previous version of KKM did not report any updates being required.

**Comment by ManlyMarco** [comment]
@CriticaI The previous version of kk manager didn't support updating patches at all so those would not be shown. The issue previous user had was only with help files being wrong, it doesn't affect the game at all. If no updates were found on this version before then send your kkmanager.log

**Comment by CriticaI** [comment]
Looks like I missed the point of the original bug report. Either way I don't think it's supposed to show patches that I already have installed, right?

**Comment by ManlyMarco** [comment]
Are you sure you have those patches installed?

**Comment by ManlyMarco** [comment]
For now patches are no longer distributed through kk manager so I'm closing the issue.
