### ISSUE TITLE
Problems with the latest 0.19 version

### ISSUE THREAD

**Issue by xzc1113** [IllusionMods/KKManager#80]
![0 18](https://user-images.githubusercontent.com/96443484/169669668-f6f2c86f-0b70-469c-8897-fece4610f422.png)
![0 19](https://user-images.githubusercontent.com/96443484/169669669-3e1ab775-88dc-4d07-a3e1-ff73b3d1618f.png)
[KKManager.log](https://github.com/IllusionMods/KKManager/files/8748371/KKManager.log)

**Comment by ManlyMarco** [comment]
Did you try going back to the previous version? Does that still work?

Do you use a proxy server? This is the only change that could cause this 
![image](https://user-images.githubusercontent.com/39247311/169681879-9ce843bb-82bd-4460-a510-5cbab51433ab.png)

**Comment by xzc1113** [comment]
I have rolled back to version 0.18 and it works fine. 

I didn't use a proxy server, because all the time I don't use a proxy server and the download speed is faster

**Comment by xzc1113** [comment]
After I replace the dll, the software works fine, thank you very much！
