### ISSUE TITLE
Question: How to use BinaryReader() to get Data from Cards

### ISSUE THREAD

**Issue by MermengM** [IllusionMods/KKManager#84]
Hello, developers
I'm a modder of illusion games .
Recently, I'm trying how to read the detailed data of chara cards.(eg: chara name,sex,or others)
I found that everyone seems to use BinaryReader() to read cards. But I'm not very proficient in binary.
After reading docs, I found that BinaryReader() seems to read data in order.
But after I actually use it, I found that I didn't know what data type it should use.
(eg. if i use ReadInt32 in first of Cards, i will get a int like 193211**** ,then if i use readString i wll get a square character.)
I think you may have some way to directly understand its composition, as if you clearly know which data the name is in.
So I would like to ask how to use BinaryReader() to obtain various data of the card.
Thank you.
(I don't know much about binary, but I find that everyone seems to intercept data directly from a spilts and then use the reader.DataType() to convert it. If this problem is very low-level, please don't mind.)

**Comment by ManlyMarco** [comment]
Read the game source and recreate the loading sequence, that's the only real way to do it. You have to know the order and type of values to read them, this information is not stored in the data itself.
