### ISSUE TITLE
Is there no new mod after 20220603?

### ISSUE THREAD

**Issue by wycstc353** [IllusionMods/KKManager#86]
Is there no new mod after 20220603? Version 0.18.0 has been used before. After version 0.19 is used, a little check of mod update shows that there is no new mod

**Comment by wycstc353** [comment]
![image](https://user-images.githubusercontent.com/39401653/187057183-9f890cca-42e1-41fa-bbd1-6f06c89d2ccb.png)

**Comment by ManlyMarco** [comment]
The modpack is temporarily not being updated. You can get latest mods by enabling experimental mode in game launcher, but be prepared for issues since these mods were not tested and potentially fixed.

This error could appear because of an internet outage or servers being blocked.
