### ISSUE TITLE
Game can't auto load the PNG files inside the UserData folder of Experimental zipmods / Bleeding Edge

### ISSUE THREAD

**Issue by RodrigoKazuma** [IllusionMods/KKManager#87]
Hi there,
I don't know where the best place to report (probably) a bug on KKManager Update tool, so I will do it here:
The game can't find the png files inside the UserData folder that comes with the experimental (Bleeding Edge) zipmods.

A simple way to fix this is the Betterrepack team to create a new Bleeding Edge folder inside all the UserData pngs folders (like UserData\chara\female\Bleeding Egde), and then move all the pngs from "Sideloader Modpack - Bleeding Edge" to the new folder.

**Comment by ManlyMarco** [comment]
Sounds like it's an issue with the modpack rather than KKManager itself. In that case it's better to post the issue here https://github.com/BetterRepack/SideloaderModpackTracker/issues
