### ISSUE TITLE
Mannually download files without using StandAloneUpdater will help you solve issues related to download speed

### ISSUE THREAD

**Issue by yyuurrii34** [IllusionMods/KKManager#99]
Example:

ftp://sideloader:sideloader3@185.141.63.59:2121/AI/mods/Sideloader%20Modpack%20-%20Studio/Conquestus/%5BConquestus%5D%20Living%20Room%201%20v1.00.zipmod

![downloadstatus](https://user-images.githubusercontent.com/46563122/205469610-8c44b0ed-2e0e-4a8e-b2dd-45c8b2554c13.png)

#55 #91 
@ssj4maiko @zhxpz @x94fujo6rpg

**Comment by QWdfASer** [comment]
Would you mind giving a short tutorial on how to do that? Trying for months to download with KKmanager without success and i don't how to download with FTP.

**Comment by setho123113** [comment]
Can you teach me how to do this? I really want to do this since the download speeds for KKManager is really slow.

**Comment by ssj4maiko** [comment]
he is just using an FTP client, and accessing everything via FTP.

The other option is to use https://github.com/RobotsOnDrugs/BDSM which has been working well for me, and does basically the same thing.

**Comment by ManlyMarco** [comment]
Obsolete since 0.21.0
